package com.haolaike.hotlikescan.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.haolaike.hotlikescan.beans.LogBeans;
import com.haolaike.hotlikescan.beans.PartsBean;

import com.haolaike.hotlikescan.dao.LogBeansDao;
import com.haolaike.hotlikescan.dao.PartsBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig logBeansDaoConfig;
    private final DaoConfig partsBeanDaoConfig;

    private final LogBeansDao logBeansDao;
    private final PartsBeanDao partsBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        logBeansDaoConfig = daoConfigMap.get(LogBeansDao.class).clone();
        logBeansDaoConfig.initIdentityScope(type);

        partsBeanDaoConfig = daoConfigMap.get(PartsBeanDao.class).clone();
        partsBeanDaoConfig.initIdentityScope(type);

        logBeansDao = new LogBeansDao(logBeansDaoConfig, this);
        partsBeanDao = new PartsBeanDao(partsBeanDaoConfig, this);

        registerDao(LogBeans.class, logBeansDao);
        registerDao(PartsBean.class, partsBeanDao);
    }
    
    public void clear() {
        logBeansDaoConfig.clearIdentityScope();
        partsBeanDaoConfig.clearIdentityScope();
    }

    public LogBeansDao getLogBeansDao() {
        return logBeansDao;
    }

    public PartsBeanDao getPartsBeanDao() {
        return partsBeanDao;
    }

}
